/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R18B.Group5.VendingMachine;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        MainProcessor processor = new MainProcessor();
        MainWindow mainWindow = new MainWindow(processor);
        primaryStage.setScene(mainWindow.getScene());
        primaryStage.setTitle("Vending Machine");
        primaryStage.show();
    }

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        launch(args);
    }
}
