/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VendingMachine;

import VendingMachine.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testGreeting() {
        App app = new App();
        assertEquals("Hello world.", app.getGreeting());
    }
}
